// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuR-j137t2DgQAEDxFp38lc8JmAQiPXCs',
    appId: '1:810004665204:web:c405fb978634c623dad221',
    messagingSenderId: '810004665204',
    projectId: 'application-flutter1',
    authDomain: 'application-flutter1.firebaseapp.com',
    storageBucket: 'application-flutter1.appspot.com',
    measurementId: 'G-GHM6Q5G8NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUPsDg3QpGFkRFn7YzBPDRqHYCpjiNXI',
    appId: '1:810004665204:android:e020728b8fd0c04fdad221',
    messagingSenderId: '810004665204',
    projectId: 'application-flutter1',
    storageBucket: 'application-flutter1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_TdnXPp14vkyL__6oTyCyYClGHiRmYa4',
    appId: '1:810004665204:ios:9275c6faccd4edffdad221',
    messagingSenderId: '810004665204',
    projectId: 'application-flutter1',
    storageBucket: 'application-flutter1.appspot.com',
    iosClientId: '810004665204-hgaqppfsnj1drngbiufstl57298pqrit.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_TdnXPp14vkyL__6oTyCyYClGHiRmYa4',
    appId: '1:810004665204:ios:9275c6faccd4edffdad221',
    messagingSenderId: '810004665204',
    projectId: 'application-flutter1',
    storageBucket: 'application-flutter1.appspot.com',
    iosClientId: '810004665204-hgaqppfsnj1drngbiufstl57298pqrit.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupName',
  );
}
